# Generated by Django 5.0.3 on 2024-03-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_candidate_w3id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='unique_id',
            field=models.CharField(max_length=50),
        ),
    ]
