# Generated by Django 5.0.3 on 2024-03-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_vote_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='otp',
            field=models.BigIntegerField(null=True),
        ),
    ]
